version: '3'
services:
  centos7:
    image: centos 
    container_name: centos7
    restart: always
    entrypoint: "sleep infinity"

  ubuntu:
    image: pycontribs/ubuntu 
    container_name: ubuntu 
    restart: always
    entrypoint: "sleep infinity"
